const fs=require('fs'),path=require('path');
const clean=v=>String(v||'').trim().replace(/^["']|["']$/g,'');
const truthy=v=>/^(true|1|yes|on)$/i.test(String(v||''));
function parse(t=''){const o={};for(const line of t.replace(/\r/g,'').split('\n')){const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$/);if(m)o[m[1]]=clean(m[2]);}return o;}
function collection(dir){if(!fs.existsSync(dir))return[];return fs.readdirSync(dir).filter(f=>/\.md$/i.test(f)&&!f.startsWith('.')).map(f=>{const t=fs.readFileSync(path.join(dir,f),'utf8'),fm=t.startsWith('---')?(t.split(/^---\s*$/m).slice(1,2)[0]||''):t;return parse(fm);});}
function text(s=''){return s.replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();}
// PRESS: allow hiding every legacy item and reorder the MORE PRESS cards. The featured card keeps its design slot.
if(fs.existsSync('press.html')){let h=fs.readFileSync('press.html','utf8'),items=collection('data/press'),byTitle=new Map(items.map(x=>[x.title,x]));const re=/<a\b[^>]*class=["'][^"']*press-(?:feature|small)[^"']*["'][^>]*>[\s\S]*?<\/a>/gi;const blocks=h.match(re)||[];for(const b of blocks){const title=text((b.match(/<h[23][^>]*>([\s\S]*?)<\/h[23]>/i)||[])[1]||''),it=byTitle.get(title);if(it&&truthy(it.hidden))h=h.replace(b,'');}
 const moreRe=/(<div class=["']more-press["']>)([\s\S]*?)(<\/div>\s*(?:<\/section>)?)/i,m=h.match(moreRe);if(m){const small=m[2].match(/<a\b[^>]*class=["'][^"']*press-small[^"']*["'][^>]*>[\s\S]*?<\/a>/gi)||[];const ranked=small.map((b,i)=>{const title=text((b.match(/<h3[^>]*>([\s\S]*?)<\/h3>/i)||[])[1]||''),it=byTitle.get(title);return{b,order:Number((it&&it.order)||((i+1)*10))};}).sort((a,b)=>a.order-b.order).map(x=>x.b).join('');let middle=m[2];for(const b of small)middle=middle.replace(b,'');h=h.replace(moreRe,`${m[1]}${middle}${ranked}${m[3]}`);}fs.writeFileSync('press.html',h,'utf8');console.log('LACROMA: applied Press hide/order controls');}
// EXHIBITIONS: hide and reorder all existing exhibition sections.
if(fs.existsSync('exhibitions.html')){let h=fs.readFileSync('exhibitions.html','utf8'),items=collection('data/exhibitions'),byTitle=new Map(items.map(x=>[x.title,x]));const re=/<section\b[^>]*class=["'][^"']*exhibition[^"']*["'][^>]*>[\s\S]*?<\/section>/gi,blocks=h.match(re)||[];if(blocks.length){const firstPos=h.indexOf(blocks[0]);let stripped=h;for(const b of blocks)stripped=stripped.replace(b,'');const ranked=blocks.map((b,i)=>{const title=text((b.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)||[])[1]||''),it=byTitle.get(title);return{b,it,order:Number((it&&it.order)||((i+1)*10))};}).filter(x=>!(x.it&&truthy(x.it.hidden))).sort((a,b)=>a.order-b.order).map(x=>x.b).join('');h=stripped.slice(0,firstPos)+ranked+stripped.slice(firstPos);fs.writeFileSync('exhibitions.html',h,'utf8');console.log('LACROMA: applied Exhibitions hide/order controls');}}
