backend:
  name: github
  repo: ninodjula-debug/lacroma
  branch: main

media_folder: "media"
public_folder: "/media"

collections:
  - name: "works"
    label: "Works"
    folder: "data/works"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Places", "Faces", "Notes", "Objects"]
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Location", name: "location", widget: "string", required: false }
